name: CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies
        run: npm ci

      - name: Check Prettier
        run: npm run prettier

  lint-functions:
    name: Lint Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies
        working-directory: ./functions
        run: npm ci

      - name: Lint
        working-directory: ./functions
        run: npm run lint

  build-functions:
    name: Build Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies
        working-directory: ./functions
        run: npm ci

      - name: Build
        working-directory: ./functions
        run: npm run build

  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies
        working-directory: ./client
        run: npm ci

      - name: Lint
        working-directory: ./client
        run: npm run lint

  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies
        working-directory: ./client
        run: npm ci

      - name: Build
        working-directory: ./client
        run: npm run build:prod

  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install Node Dependencies in Client
        working-directory: ./client
        run: npm ci

      - name: Install Node Dependencies in Function
        working-directory: ./function
        run: npm ci

      - name: Install firebase emulators
        run: npm i -g firebase-tools

      - name: Install Playwright
        working-directory: ./client
        run: npx playwright install --with-deps

      - name: Test
        working-directory: ./client
        run: npm run test

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    needs: [prettier, lint-functions, build-functions, lint-client, build-client, playwright]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies in Client
        working-directory: ./client
        run: npm ci

      - name: Install Node Dependencies in Function
        working-directory: ./function
        run: npm ci

      - name: Build Functions
        working-directory: ./functions
        run: npm run build

      - name: Build Client
        working-directory: ./client
        run: npm run build:stage

      - name: Install firebase
        run: npm i -g firebase-tools

      - name: Deploy
        run: firebase deploy --project stage --message "${{ github.event.head_commit.message }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    needs: [prettier, lint-functions, build-functions, lint-client, build-client, playwright]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies in Client
        working-directory: ./client
        run: npm ci

      - name: Install Node Dependencies in Function
        working-directory: ./function
        run: npm ci

      - name: Build Functions
        working-directory: ./functions
        run: npm run build

      - name: Build Client
        working-directory: ./client
        run: npm run build:stage

      - name: Install firebase
        run: npm i -g firebase-tools

      - name: Deploy
        run: firebase deploy --project prod --message "${{ github.event.head_commit.message }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
